apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberambassador-backend
  namespace: cyber-ambassador
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: cyberambassador-backend
spec:
  selector:
    matchLabels:
      app: cyberambassador-backend
  template:
    metadata:
      labels:
        app: cyberambassador-backend
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"

      containers:
        - name: backend
          image: finriustech/cyberambassador-backend:dff67d0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3000

          # ✅ LOAD ENVS FROM CONFIGMAP + SEALED SECRET
          envFrom:
            - configMapRef:
                name: cyberambassador
            - secretRef:
                name: cyberambassador

          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

          volumeMounts:
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: tmp
          emptyDir: {}
