apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cyberambassador-backend-hpa
  namespace: cyber-ambassador
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cyberambassador-backend

  minReplicas: 1
  maxReplicas: 3

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
