apiVersion: v1
kind: Service
metadata:
  name: cyberambassador-postgres-headless
  namespace: cyber-ambassador
  labels:
    app: cyberambassador-postgres
spec:
  clusterIP: None
  selector:
    app: cyberambassador-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
