apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cyberambassador-https
  namespace: cyber-ambassador
spec:
  parentRefs:
    - name: solvox-gateway
      namespace: gateway-system
      sectionName: https

  hostnames:
    - api.cyberambassador.co.in

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Strict-Transport-Security
                value: "max-age=63072000; includeSubDomains; preload"

              - name: X-Frame-Options
                value: "DENY"

              - name: X-Content-Type-Options
                value: "nosniff"

              - name: Referrer-Policy
                value: "strict-origin-when-cross-origin"

              - name: Permissions-Policy
                value: "geolocation=(), microphone=(), camera=()"

              - name: Content-Security-Policy
                value: "default-src 'self'; style-src 'self' 'unsafe-inline' https://stackpath.bootstrapcdn.com; img-src 'self' data:; font-src 'self' data:; frame-ancestors 'none'; object-src 'none'; base-uri 'self';"

      backendRefs:
        - name: cyberambassador-backend
          namespace: cyber-ambassador
          port: 80
